//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALBUMDETAIL
    {
        public int ID { get; set; }
        public int ID_ALBUM { get; set; }
        public string IMAGE_URL { get; set; }
        public int TRANG_THAI { get; set; }
        public bool DAI_DIEN { get; set; }
    }
}
