//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class BIEU_QUYET
    {
        public int ID { get; set; }
        public int ID_DANHMUC_BIEUQUYET { get; set; }
        public string BIEUQUYET { get; set; }
        public int THU_TU { get; set; }
        public int SO_LUONG { get; set; }
        public string IP_TAO { get; set; }
        public System.DateTime NGAY_TAO { get; set; }
        public string IP_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public string IP_XOA { get; set; }
        public Nullable<System.DateTime> NGAY_XOA { get; set; }
        public int TRANG_THAI { get; set; }
    
        public virtual DANHMUC_BIEUQUYET DANHMUC_BIEUQUYET { get; set; }
    }
}
