//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUNGNHAN
    {
        public int ID { get; set; }
        public string TIEU_DE { get; set; }
        public string IMG { get; set; }
        public Nullable<System.DateTime> NGAY { get; set; }
        public Nullable<int> TRANG_THAI { get; set; }
    }
}
