//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKYHOC_SYN
    {
        public int ID { get; set; }
        public string HoTen { get; set; }
        public string HKTTruId { get; set; }
        public Nullable<System.DateTime> NgayNhanHSo { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string GioiTinh { get; set; }
        public string KhoahocId { get; set; }
    }
}
