//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKYHOC
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> KhoahocId { get; set; }
        public string SoGPLX { get; set; }
        public Nullable<int> HangGPLXId { get; set; }
        public Nullable<System.DateTime> NgayTT { get; set; }
        public Nullable<System.DateTime> Ngaycap { get; set; }
        public Nullable<System.DateTime> Ngayhethan { get; set; }
        public string Donvicap { get; set; }
        public string Ghichu { get; set; }
        public System.DateTime Ngaydangky { get; set; }
        public Nullable<bool> DaChuyen { get; set; }
        public Nullable<bool> DaThanhtoan { get; set; }
        public Nullable<System.DateTime> NgayThanhtoan { get; set; }
        public string NganluongToken { get; set; }
    }
}
