//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DANGKY
    {
        public int ID { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string SODIENTHOAI { get; set; }
        public string EMAIL { get; set; }
        public int IDLOPHOC { get; set; }
        public string NOIDUNG { get; set; }
        public System.DateTime NGAYDANGKY { get; set; }
        public int TRANGTHAI { get; set; }
    }
}
