//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_DVHC
    {
        public string MaDvhc { get; set; }
        public string MaDVQL { get; set; }
        public string MaDV { get; set; }
        public string TenDvhc { get; set; }
        public string TenNganGon { get; set; }
        public string TenDayDu { get; set; }
        public string LoaiDvhc { get; set; }
        public string GhiChu { get; set; }
        public bool TrangThai { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgaySua { get; set; }
    }
}
