//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_HANGDT
    {
        public string MaHangDT { get; set; }
        public string TenHangDT { get; set; }
        public string HangGPLX { get; set; }
        public string SoVBPL { get; set; }
        public Nullable<int> TuoiHV { get; set; }
        public Nullable<int> ThamNien { get; set; }
        public Nullable<int> KmLXAT { get; set; }
        public string DKSH { get; set; }
        public string MucTieuDT { get; set; }
        public string GhiChu { get; set; }
        public bool TrangThai { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
        public System.DateTime NgayTao { get; set; }
        public System.DateTime NgaySua { get; set; }
    }
}
