//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesData : DbContext
    {
        public EntitiesData()
            : base("name=EntitiesData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ACTIONLOG> ACTIONLOGs { get; set; }
        public virtual DbSet<ALBUM> ALBUMs { get; set; }
        public virtual DbSet<ALBUMDETAIL> ALBUMDETAILs { get; set; }
        public virtual DbSet<BACKGROUND> BACKGROUNDs { get; set; }
        public virtual DbSet<BAI_VIET> BAI_VIET { get; set; }
        public virtual DbSet<BAIVIET_LIENQUAN> BAIVIET_LIENQUAN { get; set; }
        public virtual DbSet<BANNER> BANNERs { get; set; }
        public virtual DbSet<BIEU_QUYET> BIEU_QUYET { get; set; }
        public virtual DbSet<CART> CARTs { get; set; }
        public virtual DbSet<CART_STATUS> CART_STATUS { get; set; }
        public virtual DbSet<CHUNGNHAN> CHUNGNHANs { get; set; }
        public virtual DbSet<CHUYEN_MUC> CHUYEN_MUC { get; set; }
        public virtual DbSet<COMMENT> COMMENTs { get; set; }
        public virtual DbSet<COQUAN_BANHANH> COQUAN_BANHANH { get; set; }
        public virtual DbSet<DANGKY> DANGKies { get; set; }
        public virtual DbSet<DANGKYHOC> DANGKYHOCs { get; set; }
        public virtual DbSet<DANGKYHOC_SYN> DANGKYHOC_SYN { get; set; }
        public virtual DbSet<DANHMUC_BIEUQUYET> DANHMUC_BIEUQUYET { get; set; }
        public virtual DbSet<DM_DVHC> DM_DVHC { get; set; }
        public virtual DbSet<DM_GIOITINH> DM_GIOITINH { get; set; }
        public virtual DbSet<DM_HANGDT> DM_HANGDT { get; set; }
        public virtual DbSet<DM_HANGGP> DM_HANGGP { get; set; }
        public virtual DbSet<DM_QUOCTICH> DM_QUOCTICH { get; set; }
        public virtual DbSet<HOI_DAP> HOI_DAP { get; set; }
        public virtual DbSet<KHOAHOC> KHOAHOCs { get; set; }
        public virtual DbSet<LIEN_KET> LIEN_KET { get; set; }
        public virtual DbSet<LOAI_HIENTHI> LOAI_HIENTHI { get; set; }
        public virtual DbSet<LOAIHINHDAOTAO> LOAIHINHDAOTAOs { get; set; }
        public virtual DbSet<LOGO> LOGOes { get; set; }
        public virtual DbSet<LUOT_TRUY_CAP> LUOT_TRUY_CAP { get; set; }
        public virtual DbSet<MENU> MENUs { get; set; }
        public virtual DbSet<NGUOI_VIETBAI> NGUOI_VIETBAI { get; set; }
        public virtual DbSet<NHOM_BAIVIET> NHOM_BAIVIET { get; set; }
        public virtual DbSet<NHOM_VANBAN> NHOM_VANBAN { get; set; }
        public virtual DbSet<ORDER> ORDERs { get; set; }
        public virtual DbSet<ORDER_DETAIL> ORDER_DETAIL { get; set; }
        public virtual DbSet<ORDER_STATUS> ORDER_STATUS { get; set; }
        public virtual DbSet<PHANQUYEN_CHUYENMUC> PHANQUYEN_CHUYENMUC { get; set; }
        public virtual DbSet<PHANQUYEN_MENU> PHANQUYEN_MENU { get; set; }
        public virtual DbSet<PRODUCT> PRODUCTs { get; set; }
        public virtual DbSet<PRODUCTCATELOGY> PRODUCTCATELOGies { get; set; }
        public virtual DbSet<RATING> RATINGs { get; set; }
        public virtual DbSet<ROLEINGROUP> ROLEINGROUPs { get; set; }
        public virtual DbSet<SAN_PHAM_ALBUM> SAN_PHAM_ALBUM { get; set; }
        public virtual DbSet<SLIDE> SLIDEs { get; set; }
        public virtual DbSet<SLIDEBANNER> SLIDEBANNERs { get; set; }
        public virtual DbSet<SLOGAN> SLOGANs { get; set; }
        public virtual DbSet<SPECIFICROLE> SPECIFICROLEs { get; set; }
        public virtual DbSet<SUB_BANNER> SUB_BANNER { get; set; }
        public virtual DbSet<SUB_BANNER_> SUB_BANNER_ { get; set; }
        public virtual DbSet<TOKEN> TOKENs { get; set; }
        public virtual DbSet<USERDETAIL> USERDETAILS { get; set; }
        public virtual DbSet<VANBAN> VANBANs { get; set; }
        public virtual DbSet<VIDEO> VIDEOs { get; set; }
        public virtual DbSet<webpages_Membership> webpages_Membership { get; set; }
        public virtual DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public virtual DbSet<webpages_Roles> webpages_Roles { get; set; }
        public virtual DbSet<webpages_UserProfile> webpages_UserProfile { get; set; }
        public virtual DbSet<webpages_UsersInRoles> webpages_UsersInRoles { get; set; }
        public virtual DbSet<UU_DIEM> UU_DIEM { get; set; }
        public virtual DbSet<THONG_TIN> THONG_TIN { get; set; }
    
        public virtual int Capnhat_Baiviet_Lienquan(Nullable<int> id, Nullable<int> id_bv_lq)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_bv_lqParameter = id_bv_lq.HasValue ?
                new ObjectParameter("id_bv_lq", id_bv_lq) :
                new ObjectParameter("id_bv_lq", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Capnhat_Baiviet_Lienquan", idParameter, id_bv_lqParameter);
        }
    
        public virtual int Insert_HocVien_Syn(string hoten, string hKTTruId, Nullable<System.DateTime> ngaySinh, Nullable<System.DateTime> ngayNhanHSo, string gioiTinh, string maKh)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var hKTTruIdParameter = hKTTruId != null ?
                new ObjectParameter("HKTTruId", hKTTruId) :
                new ObjectParameter("HKTTruId", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var ngayNhanHSoParameter = ngayNhanHSo.HasValue ?
                new ObjectParameter("NgayNhanHSo", ngayNhanHSo) :
                new ObjectParameter("NgayNhanHSo", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var maKhParameter = maKh != null ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_HocVien_Syn", hotenParameter, hKTTruIdParameter, ngaySinhParameter, ngayNhanHSoParameter, gioiTinhParameter, maKhParameter);
        }
    
        public virtual int Insert_HocVien_Syn1(string hoten, string hKTTruId, Nullable<System.DateTime> ngaySinh, Nullable<System.DateTime> ngayNhanHSo, string gioiTinh, string maKh)
        {
            var hotenParameter = hoten != null ?
                new ObjectParameter("Hoten", hoten) :
                new ObjectParameter("Hoten", typeof(string));
    
            var hKTTruIdParameter = hKTTruId != null ?
                new ObjectParameter("HKTTruId", hKTTruId) :
                new ObjectParameter("HKTTruId", typeof(string));
    
            var ngaySinhParameter = ngaySinh.HasValue ?
                new ObjectParameter("NgaySinh", ngaySinh) :
                new ObjectParameter("NgaySinh", typeof(System.DateTime));
    
            var ngayNhanHSoParameter = ngayNhanHSo.HasValue ?
                new ObjectParameter("NgayNhanHSo", ngayNhanHSo) :
                new ObjectParameter("NgayNhanHSo", typeof(System.DateTime));
    
            var gioiTinhParameter = gioiTinh != null ?
                new ObjectParameter("GioiTinh", gioiTinh) :
                new ObjectParameter("GioiTinh", typeof(string));
    
            var maKhParameter = maKh != null ?
                new ObjectParameter("MaKh", maKh) :
                new ObjectParameter("MaKh", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_HocVien_Syn1", hotenParameter, hKTTruIdParameter, ngaySinhParameter, ngayNhanHSoParameter, gioiTinhParameter, maKhParameter);
        }
    
        public virtual int Insert_PhanQuyen_Menu(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PhanQuyen_Menu", idParameter);
        }
    
        public virtual int Insert_PhanQuyen_NhomBaiViet(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Insert_PhanQuyen_NhomBaiViet", idParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> luottruycap_homnay()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("luottruycap_homnay");
        }
    
        public virtual int Reset_Baiviet_Lienquan(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reset_Baiviet_Lienquan", idParameter);
        }
    
        public virtual int Reset_Hienthi_Banner(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reset_Hienthi_Banner", idParameter);
        }
    
        public virtual int Reset_Hienthi_Logo(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Reset_Hienthi_Logo", idParameter);
        }
    
        public virtual ObjectResult<sp_LAY_DS_BACKGROUND_Result> sp_LAY_DS_BACKGROUND()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_BACKGROUND_Result>("sp_LAY_DS_BACKGROUND");
        }
    
        public virtual ObjectResult<sp_LAY_DS_BANNER_Result> sp_LAY_DS_BANNER()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_BANNER_Result>("sp_LAY_DS_BANNER");
        }
    
        public virtual ObjectResult<sp_LAY_DS_CHUNG_NHAN_Result> sp_LAY_DS_CHUNG_NHAN()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_CHUNG_NHAN_Result>("sp_LAY_DS_CHUNG_NHAN");
        }
    
        public virtual ObjectResult<sp_LAY_DS_COMMENT_Result> sp_LAY_DS_COMMENT(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_COMMENT_Result>("sp_LAY_DS_COMMENT", idParameter);
        }
    
        public virtual ObjectResult<sp_LAY_DS_DANHMUC_SANPHAM_Result> sp_LAY_DS_DANHMUC_SANPHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_DANHMUC_SANPHAM_Result>("sp_LAY_DS_DANHMUC_SANPHAM");
        }
    
        public virtual ObjectResult<sp_LAY_DS_LIEN_KET_Result> sp_LAY_DS_LIEN_KET()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_LIEN_KET_Result>("sp_LAY_DS_LIEN_KET");
        }
    
        public virtual ObjectResult<sp_LAY_DS_LIEN_QUAN_Result> sp_LAY_DS_LIEN_QUAN(Nullable<int> id_nbv, Nullable<int> id_bv)
        {
            var id_nbvParameter = id_nbv.HasValue ?
                new ObjectParameter("id_nbv", id_nbv) :
                new ObjectParameter("id_nbv", typeof(int));
    
            var id_bvParameter = id_bv.HasValue ?
                new ObjectParameter("id_bv", id_bv) :
                new ObjectParameter("id_bv", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_LIEN_QUAN_Result>("sp_LAY_DS_LIEN_QUAN", id_nbvParameter, id_bvParameter);
        }
    
        public virtual ObjectResult<sp_LAY_DS_LOGO_Result> sp_LAY_DS_LOGO()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_LOGO_Result>("sp_LAY_DS_LOGO");
        }
    
        public virtual ObjectResult<sp_LAY_DS_MENU_CHA_Result> sp_LAY_DS_MENU_CHA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_MENU_CHA_Result>("sp_LAY_DS_MENU_CHA");
        }
    
        public virtual ObjectResult<sp_LAY_DS_MENU_CON_THEO_MENU_CHA_Result> sp_LAY_DS_MENU_CON_THEO_MENU_CHA(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_MENU_CON_THEO_MENU_CHA_Result>("sp_LAY_DS_MENU_CON_THEO_MENU_CHA", idParameter);
        }
    
        public virtual ObjectResult<sp_LAY_DS_SAN_PHAM_Result> sp_LAY_DS_SAN_PHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_LAY_DS_SAN_PHAM_Result>("sp_LAY_DS_SAN_PHAM");
        }
    
        public virtual ObjectResult<Nullable<int>> sp_lay_luot_truycap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_lay_luot_truycap");
        }
    
        public virtual int sp_tang_luot_truycap()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_tang_luot_truycap");
        }
    
        public virtual ObjectResult<sp_TimKiem_Result> sp_TimKiem(string searchtext)
        {
            var searchtextParameter = searchtext != null ?
                new ObjectParameter("searchtext", searchtext) :
                new ObjectParameter("searchtext", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_Result>("sp_TimKiem", searchtextParameter);
        }
    
        public virtual ObjectResult<sp_TimKiem_VanBan_Result> sp_TimKiem_VanBan(string searchtext, Nullable<int> combo, Nullable<int> year, Nullable<int> combo_coquan)
        {
            var searchtextParameter = searchtext != null ?
                new ObjectParameter("searchtext", searchtext) :
                new ObjectParameter("searchtext", typeof(string));
    
            var comboParameter = combo.HasValue ?
                new ObjectParameter("combo", combo) :
                new ObjectParameter("combo", typeof(int));
    
            var yearParameter = year.HasValue ?
                new ObjectParameter("year", year) :
                new ObjectParameter("year", typeof(int));
    
            var combo_coquanParameter = combo_coquan.HasValue ?
                new ObjectParameter("combo_coquan", combo_coquan) :
                new ObjectParameter("combo_coquan", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_TimKiem_VanBan_Result>("sp_TimKiem_VanBan", searchtextParameter, comboParameter, yearParameter, combo_coquanParameter);
        }
    
        public virtual int Update_PhanQuyen_Menu(Nullable<int> id_user)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_PhanQuyen_Menu", id_userParameter);
        }
    
        public virtual int Update_PhanQuyen_Nhombaiviet(Nullable<int> id_user)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Update_PhanQuyen_Nhombaiviet", id_userParameter);
        }
    }
}
