//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOI_DAP
    {
        public int ID { get; set; }
        public bool HIEN_THI { get; set; }
        public string NGUOI_HOI { get; set; }
        public string EMAIL { get; set; }
        public string CAU_HOI { get; set; }
        public string TRA_LOI { get; set; }
        public System.DateTime NGAY_DANG { get; set; }
        public int TRANG_THAI { get; set; }
        public string DIA_CHI { get; set; }
        public string PHONE { get; set; }
    }
}
