//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHOAHOC
    {
        public int KhoaId { get; set; }
        public string Ten { get; set; }
        public Nullable<int> HangGPId { get; set; }
        public Nullable<int> LoaihinhDaotaoId { get; set; }
        public Nullable<System.DateTime> Khaigiang { get; set; }
        public Nullable<System.DateTime> Begiang { get; set; }
        public Nullable<System.DateTime> Ngaythi { get; set; }
        public Nullable<System.DateTime> Sathach { get; set; }
        public Nullable<int> SoHVien { get; set; }
        public Nullable<int> Tuoitoithieu { get; set; }
        public Nullable<double> Hocphi { get; set; }
        public string MAPID { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> Trangthai { get; set; }
    }
}
