//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIHINHDAOTAO
    {
        public int Id { get; set; }
        public int Thoigian { get; set; }
        public int HangSId { get; set; }
        public int HangDId { get; set; }
    }
}
