//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class THONG_TIN
    {
        public int ID { get; set; }
        public string TEN_DONVI { get; set; }
        public string DIACHI_DONVI { get; set; }
        public string GIAY_PHEP { get; set; }
        public string SDT { get; set; }
        public string DIDONG { get; set; }
        public string EMAIL { get; set; }
        public string FAX { get; set; }
        public string LATITUDE { get; set; }
        public string LONGTITUDE { get; set; }
        public string THIET_KE { get; set; }
        public string IP_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public string FACEBOOK { get; set; }
        public string CHAOMUNG { get; set; }
        public string MAP_IMG { get; set; }
        public string MAP_LINK { get; set; }
        public string VIDEO_LINK { get; set; }
    }
}
