//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TLBD.Models.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIDEO
    {
        public int ID { get; set; }
        public string TEN_VIDEO { get; set; }
        public string GHI_CHU { get; set; }
        public string FILE_LOGO { get; set; }
        public string FILE_VIDEO { get; set; }
        public bool NOIBAT { get; set; }
        public string IP_TAO { get; set; }
        public System.DateTime NGAY_TAO { get; set; }
        public string IP_SUA { get; set; }
        public Nullable<System.DateTime> NGAY_SUA { get; set; }
        public string IP_XOA { get; set; }
        public Nullable<System.DateTime> NGAY_XOA { get; set; }
        public int TRANG_THAI { get; set; }
    }
}
